### PR TITLE
Import opn for dev-server

### PR DESCRIPTION
**Pull request by luventa**
module opn can open web browser automatically for dev env. 
And it's already implemented in vue-cli webpack template.

### CODE REVIEW

**Comment by fundon** [comment]
Thank you!

Please rebase the commits.

**Comment by luventa** [comment]
appologize, network latency makes me cannot rebase my commits in office...
will do once I get home.
Thank you!

**Comment by luventa** [comment]
I'm really sorry that I'm still a newbie with git...
I did follow the git guideline but it seems I did commit wrong files
plus, my network is much more disgusting at home....that's I close the PR for time being...
I will and need do some reach in git usage

**Comment by fundon** [comment]
See http://stackoverflow.com/questions/2563632/how-can-i-merge-two-commits-into-one

**Comment by luventa** [comment]
thanks a lot!
I'm looking into that now.
I use shadowsocks/vpn to improve my net speed but both of them are useless...The speed of cloning project at home is less than 5kb/s....

**Pull request closed without merging**
